language: python
python:
  - 3.7
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
  - pip install -r requirements.dev.txt
install:
  - make certs
  - make generate
  - make style.check
  - make dist
  - pip install dist/gestalt-*.whl
script:
  - make test
  - make docs
