dist: xenial   # required for Python >= 3.7
addons:
  apt:
    packages:
    - rabbitmq-server

language: python
python:
  - 3.6
  - 3.7
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
  - pip install -r requirements.dev.txt
install:
  - make certs
  - make generate
  - pip install .[amq,protobuf,msgpack,avro,brotli,yaml]
script:
  - make style.check
  - make test
  - make docs
  - make dist
