dist: xenial   # required for Python >= 3.7
addons:
  apt:
    packages:
    - rabbitmq-server

language: python
python:
  - 3.6
  - 3.7
os:
  - linux
git:
  depth: 1
before_install:
  - sudo apt-get install libsnappy-dev
  - pip install pip --upgrade
  - pip install -r requirements.dev.txt
install:
  - make certs
  - make generate
  - pip install .[amq,protobuf,msgpack,avro,brotli,snappy,yaml]
script:
  - make check-style
  - make-check-types
  - make check-coverage
  - make docs
  - make dist
